### ISSUE TITLE
No way to successfully import under python 3.7

### ISSUE THREAD

**Issue by fengnex** [eficode/robotframework-imagehorizonlibrary#49]
Got the following exception when executing the example file "calculator.robot" after executing "python setup.py install":
Additional info: Following exception has been thrown:
            Traceback (most recent call last):
              File "C:\Users\ADMINI~1\AppData\Local\Temp\RobotTempDir2110408418075580461\robot_session_server.py", line 43, in inner
                result['result'] = func(*args, **kwargs)
              File "C:\Users\ADMINI~1\AppData\Local\Temp\RobotTempDir2110408418075580461\robot_session_server.py", line 105, in inner
                return to_call(*args, **kwargs)
              File "C:\Users\ADMINI~1\AppData\Local\Temp\RobotTempDir2110408418075580461\robot_session_server.py", line 138, in inner
                return to_call(*args, **kwargs)
              File "C:\Users\ADMINI~1\AppData\Local\Temp\RobotTempDir2110408418075580461\robot_session_server.py", line 78, in inner
                return func(*args, **kwargs)
              File "C:\Users\ADMINI~1\AppData\Local\Temp\RobotTempDir2110408418075580461\robot_session_server.py", line 182, in get_classes_from_module
                return red_module_classes.get_classes_from_module(module_location)
              File "C:\Users\ADMINI~1\AppData\Local\Temp\RobotTempDir2110408418075580461\red_module_classes.py", line 25, in get_classes_from_module
                inside_file_names = module_names_collector._try_to_find_names_in_module(module_name, module_location)
              File "C:\Users\ADMINI~1\AppData\Local\Temp\RobotTempDir2110408418075580461\red_module_classes.py", line 188, in _try_to_find_names_in_module
                with open(module_location, 'r', encoding='utf-8') as f:
            FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ProgramData\\Anaconda3\\lib\\site-packages\\robotframework_imagehorizonlibrary-0.2_devel-py3.7.egg\\ImageHorizonLibrary\\__init__.py'

**Comment by Tattoo** [comment]
I just tested `python setup.py install` on Windows 7 and 10 and it works as expected from command line on Python 3.8.

If I may hazard a guess, your error message seems to indicate you are maybe using RED editor? And that the error might be coming from there? Anyway, that's very different from how Python & Robot error messages look from command line. You could try running the calculator by hand in command prompt or powershell: `robot calculator.robot`, and tell me how it behaves? That way we can single out the possible interference from RED. 

When using `python setup.py install` dependencies are not automatically; you will probably face that next (if you haven't yet). To install everything in one go, I'd suggest you install the package directly from Github: `pip install git+https://github.com/eficode/robotframework-imagehorizonlibrary.git` -- that ought to install dependencies as well. On Windows 10, the installation also noted how to install Pillow separately with instructions, so watch out for that as well.

**Comment by fengnex** [comment]
@Tattoo Thank you first!
I did try to use the library in red editor on windows 7, but failed and I will try it again according to your tips on win 10.

**Comment by Tattoo** [comment]
As detailed in the [keyword documentation](https://eficode.github.io/robotframework-imagehorizonlibrary/doc/ImageHorizonLibrary.html), the reference image file name is the first argument and the path to the folder where reference images are is set during library import. In other words, if you have a reference image `my_reference_image.png` in folder `/some/path`, your test case should look like this:

``` RobotFramework
*** Settings ***
Library    ImageHorizonLibrary    reference_folder=/some/path

*** Test cases ***
My test
    ${location}=    Wait for    my reference image
```

There is more information and examples in the keyword documentation.

Due note that by default the recognition is pixel-perfect which, depending on your reference image, might fail in surprising ways. For example, transparent backgrounds in a reference image of an application icon are known not to match when the background behind is different due to the application icon being in different location on the desktop on Windows.

If you install opencv support, you can [decrease the precision](https://eficode.github.io/robotframework-imagehorizonlibrary/doc/ImageHorizonLibrary.html#Confidence%20Level) a little bit, so these kinds of small differences do not matter. Of course, be vigilant that you are not decreasing the precision too much so the library starts matching wrong items.
